package cmd

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/fatih/color"
	"github.com/gorilla/websocket"
	"github.com/spf13/cobra"
)

// logsCmd represents the logs command category
var logsCmd = &cobra.Command{
	Use:   "logs",
	Short: "Manage CLI logs",
	Long:  "Commands for managing and tailing logs generated by the alat CLI.",
}

// tailCmd represents the logs tail command
var tailCmd = &cobra.Command{
	Use:   "tail",
	Short: "Tail the AlatPay CLI logs",
	Long:  "Continuously streams API request logs directly in your terminal.",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Printf("Tailing logs from remote server (Ctrl+C to quit)...\n")
		relayURL := "ws://localhost:8081/ws"

		// Channel to signal application shutdown
		stopFunc := make(chan os.Signal, 1)
		signal.Notify(stopFunc, os.Interrupt, syscall.SIGTERM)

		go func() {
			retryCount := 0
			maxBackoff := 30 * time.Second

			for {
				fmt.Printf(color.CyanString("=> Connecting to log stream at %s...\n"), relayURL)
				wsConn, _, err := websocket.DefaultDialer.Dial(relayURL, nil)
				if err != nil {
					retryCount++
					backoff := time.Duration(1<<retryCount) * time.Second
					if backoff > maxBackoff {
						backoff = maxBackoff
					}

					log.Printf(color.RedString("[!] Failed to connect: %v"), err)
					fmt.Printf(color.YellowString("[-] Retrying in %v (Attempt %d)...\n"), backoff, retryCount)

					select {
					case <-time.After(backoff):
						continue
					case <-stopFunc:
						return
					}
				}

				fmt.Println(color.GreenString("Ready! Waiting for request logs..."))
				retryCount = 0 // Reset on successful connection

				for {
					_, message, err := wsConn.ReadMessage()
					if err != nil {
						log.Printf(color.RedString("\n[!] Disconnected from log stream: %v\n"), err)
						wsConn.Close()
						break // Break out of read loop to trigger reconnect
					}

					var netEvent MockEvent
					if err := json.Unmarshal(message, &netEvent); err != nil {
						continue
					}

					// Generate log style output
					statusColor := color.New(color.FgGreen).SprintFunc()
					if netEvent.Method == "DELETE" {
						statusColor = color.New(color.FgRed).SprintFunc()
					} else if netEvent.Method == "PUT" || netEvent.Method == "POST" {
						statusColor = color.New(color.FgYellow).SprintFunc()
					}

					fmt.Printf("[%d] %s %s - 200 OK\n", netEvent.Timestamp, statusColor(netEvent.Method), netEvent.Path)
				}

				// Small delay before reconnecting if we broke out of read loop
				time.Sleep(1 * time.Second)
			}
		}()

		// Wait for interrupt
		<-stopFunc

		fmt.Println("\nStopped tailing logs.")
	},
}

func init() {
	rootCmd.AddCommand(logsCmd)
	logsCmd.AddCommand(tailCmd)
}
